version: "3.9"
services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fantasy_ufc
    ports:
      - "5432:5432"
    volumes:
      - fantasy_ufc_pgdata:/var/lib/postgresql/data

volumes:
  fantasy_ufc_pgdata:
